labels:
  platform: linux/amd64

steps:
  # - name: test
  #   when:
  #     - event: push
  #       branch: main
  #     - event: pull_request
  #       repo: CoReACTER/SimpleDirectedHypergraphs.jl
  #   image: julia
  #   commands:
  #     - apt-get -y update
  #     - apt-get -y install python3-matplotlib libpython3-dev python3-dev
  #     - julia --project=. -e "import Pkg; Pkg.instantiate(); Pkg.test()"
  - name: docs
    when:
      event: push
      branch: main
    image: julia
    commands:
      - apt-get -y update
      - apt-get -y install python3-matplotlib libpython3-dev python3-dev openssh-server
      - julia --project=docs/ -e "import Pkg; Pkg.instantiate()"
      - julia --project=docs/ docs/make.jl
    environment: 
      PROJECT_ACCESS_TOKEN:
        from_secret: project_access_token
