labels:
  platform: linux/amd64

steps:
  test:
    when:
      - event: push
        branch: main
      - event: pull_request
        repo: CoReACTER/SimpleDirectedHypergraphs.jl
    image: julia
    commands:
      - apt-get -y update
      - apt-get -y install python3-matplotlib
      - julia --project=. -e "import Pkg; Pkg.instantiate(); Pkg.test()"
  docs:
    when:
      event: push
      branch: main
    image: julia
    commands:
      - apt-get -y update
      - apt-get -y install python3-matplotlib openssh-server
      - julia --project=docs/ -e "import Pkg; Pkg.instantiate(); Pkg.add(name="OpenSSL_jll", version="3.0")"
      - julia --project=docs/ -e "using OpenSSL_jll; using Documenter: DocMeta, doctest; using SimpleDirectedHypergraphs; DocMeta.setdocmeta!(SimpleDirectedHypergraphs, :DocTestSetup, :(using SimpleDirectedHypergraphs); recursive=true); doctest(SimpleDirectedHypergraphs)"
      - julia --project=docs/ docs/make.jl
    secrets: [ documenter_key, project_access_token ]
