labels:
  platform: linux/amd64

steps:
  - name: test
    when:
      - event: push
        branch: main
      - event: pull_request
        repo: CoReACTER/SimpleDirectedHypergraphs.jl
    image: julia
    commands:
      - apt-get -y update
      - apt-get -y install python3-matplotlib
      - julia --project=. -e "import Pkg; Pkg.instantiate(); Pkg.test()"
  - name: docs
    when:
      event: push
      branch: main
    image: julia
    commands:
      - apt-get -y update
      - apt-get -y install python3-matplotlib openssh-server
      - julia --project=docs/ -e "import Pkg; Pkg.instantiate(); Pkg.add(name="OpenSSL_jll", version="3.0")"
      - julia --project=docs/ docs/make.jl
    secrets: [ project_access_token ]
